### ISSUE TITLE
Page layout may be unexpected due to Quirks Mode

### ISSUE THREAD

**Issue by WarlisonAbreu** [brianpetro/smart-connect#19]
Hello, Brian, I am Warlison from Brazil. I acquired the license for Smart-Connections yesterday. First, I have to congratulate you on your work. From the brief moment I had experimenting with the plugin, I can say that we are at the beginning of something that has the potential to be more than just a plugin, and I already feel like I can't live without it, haha. You can count on my support.

I need help because when I access the program, it presents the following error:

![1](https://github.com/brianpetro/smart-connect/assets/174886206/225aab48-975f-4f62-986b-98b0d387dcd2)

![2](https://github.com/brianpetro/smart-connect/assets/174886206/6d69c782-8c4a-4d4b-92d8-4ff1a2139659)

"One or more documents in this page is in Quirks Mode, which will render the affected document(s) with quirks incompatible with the current HTML and CSS specifications. Quirks Mode exists mostly due to historical reasons. If this is not intentional, you can add or modify the DOCTYPE to be to render the page in No Quirks Mode."

If you could help me, I would be grateful.

**Comment by brianpetro** [comment]
Hi @WarlisonAbreu 

Thanks for the kind words and providing the screenshots 😊

Based on your screenshot, there should be some errors (likely in red) under the "Console" tab in the developer console.

If you can screenshot those errors then it should give me what I need to help solve this issue.

![Screenshot 2024-07-07 134926](https://github.com/brianpetro/smart-connect/assets/1886014/1ebc4e41-023e-48ab-8788-36088b4161b3)

🌴

**Comment by WarlisonAbreu** [comment]
Sure, I am eager to use it again. I want to test the possibilities that the smart-connection can achieve and share them here. The images are below:

![image](https://github.com/brianpetro/smart-connect/assets/174886206/aa7681e6-f67c-488c-96dc-bc6509ad5b62)

I believe this is because I don't have the smart-connection plugin installed in this vault. "Not sure."

**Comment by brianpetro** [comment]
@WarlisonAbreu thanks for the update

Try installing the Smart Connections plugin in that vault and see if it works then.

If so, I'll have to make a note to fix that, as it should work without having the plugin installed 🌴

**Comment by WarlisonAbreu** [comment]
![image](https://github.com/brianpetro/smart-connect/assets/174886206/b65117b8-42bf-404d-851a-ac71dc5a7d9b)


I managed to resolve it, Brian. I deactivated all my plugins and installed the smart-connect. I can't say for sure, but it seems that another plugin was causing a conflict. I will do some tests and report back here.

Thank you in advance for your support and assistance. Next month, I will definitely subscribe to the annual service. You can count on my support. Thank you.
