### ISSUE TITLE
Vault Folder Selection

### ISSUE THREAD

**Issue by ebakerisu** [brianpetro/smart-connect#2]
When I click on "Browse" to select the path to my Vault folder, I just get the pinwheel for a minute and nothing ever opens.  I am on Mac OS Sonoma 14.4.1 and v1.1.50 of the Smart Connect application.  I checked in permissions and it should have permission to my Documents folder.

**Comment by brianpetro** [comment]
Hi @ebakerisu 

Thanks for letting me know about this.

I haven't encountered this before, so please bear with me while we figure this out.

1) it's worth checking the console log for errors. There is a button at the bottom of the window that should open it. If you see anything that looks like an error, please screenshot and upload it here or in the help and support chat.

2) if you haven't already, quit the application, make sure to use "Disconnect and Quit" or click "Disconnect and Quit" when prompted. Then re-open and check the logs again for possible errors that might have occured at the start.

3) I think you might be on to something with your hunch about the permissions. Probably the best way to rule this out would be uninstalling the application and re-installing.

Let me know how that goes, and if I think of anything else I will let you know.

Sorry for the rough start, but thanks for trying Smart Connect 😊 

And I'm looking forward to getting this figured out and having you up and running soon!
🌴

**Comment by ebakerisu** [comment]
There is an error: ***@***.***


Eric Baker
VP, Astec Digital
4101 Jerome Ave. | 
Chattanooga, TN United States 37407
Office: +1.423.867.4210 | 
Mobile: +1.423.785.7184
www.astecindustries.com
From: WFH Brian ***@***.***>
Date: Tuesday, April 30, 2024 at 6:29 PM
To: brianpetro/smart-connect ***@***.***>
Cc: Eric Baker ***@***.***>, Mention ***@***.***>
Subject: Re: [brianpetro/smart-connect] Vault Folder Selection (Issue #2)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi @ebakerisu<https://github.com/ebakerisu>

Thanks for letting me know about this.

I haven't encountered this before, so please bear with me while we figure this out.

  1.  it's worth checking the console log for errors. There is a button at the bottom of the window that should open it. If you see anything that looks like an error, please screenshot and upload it here or in the help and support chat.
  2.  if you haven't already, quit the application, make sure to use "Disconnect and Quit" or click "Disconnect and Quit" when prompted. Then re-open and check the logs again for possible errors that might have occured at the start.
  3.  I think you might be on to something with your hunch about the permissions. Probably the best way to rule this out would be uninstalling the application and re-installing.

Let me know how that goes, and if I think of anything else I will let you know.

Sorry for the rough start, but thanks for trying Smart Connect 😊

And I'm looking forward to getting this figured out and having you up and running soon!
🌴
