### ISSUE TITLE
Smart Connect not connecting to vault - possible old mac problem

### ISSUE THREAD

**Issue by CSPayton8** [brianpetro/smart-connect#22]
Hello! 

I am trying to connect my new Smart Connect (I'll call "app") with the Smart Connections Obsidian plugin (I'll call "plugin"). Unfortunately, I'm getting two different errors:

1. Using plugin (which has API synced to ChatGPT4o and is functioning correctly), when I click on "connect to smart connect," I get a blank screen after two popups tell me that I have made all the embeddings and smart embeddings. However, the screen stays blank, and nothing changes in the app. 
2. In the app, when I click "connect," it cycles through repeated attempts and does not connect. 

Things I have tried:

- closing all apps and restarting computer. 
- force refreshing all embeddings
- reconnecting vault folder
- computer and plugins are all updated
- I was using icloud as my storage location, but I moved the vault to my harddrive and tried to re-sync...to no avail. 

A few notes:

- My 2015 mac air is older. 12.7.5 Monterrey
- My obsidian vault is obsidian sync
- I do not have a supporter license or key
- I do not have anything in the "custom connection" box filled out. 
- Not really sure what else could be affecting this other than age of operating system?

![Screen Shot 2024-07-15 at 3 02 57 PM](https://github.com/user-attachments/assets/59569e21-136e-46f2-be5a-5d2515000603)

**Comment by brianpetro** [comment]
Hi @CSPayton8 

Smart Connect will not connect without a connection key.

It can still be used via another tunnel server which you can learn about on my YouTube channel. 

🌴

**Comment by CSPayton8** [comment]
Understood!

I don't mind becoming a supporter, but I can't afford $200. Is it possible to support at a lower price?

If not, I can try your tunneling route. :)
________________________________

**Comment by brianpetro** [comment]
Minimum supporter amount is $100, but you can try out the Official Service for $20/month using this link https://smartconnections.app/smart-connect/

🌴
