### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by sharulhafiz** [brianpetro/smart-connect#23]
Is there a guide on how to remove this app? I can't delete the folder, it's being used.

Thank you

**Comment by brianpetro** [comment]
Hi @sharulhafiz 

It should be able to be uninstalled like any other app.

You can check if the app is currently running by looking for the icon in the system tray or task manager. Quitting the app should prevent any issues with the folder being used.

🌴

**Comment by sharulhafiz** [comment]
For those who's looking why it still start after windows restart after you remove it.

Here are the steps to correctly uninstall it.
0. Install this app again
1. Close obsidian
2. Close the apps
3. Check system tray, disconnect and quit if it's still running
4. Uninstall using the Add Remove Programs

**Comment by brianpetro** [comment]
@sharulhafiz thanks for adding those details 😊 🌴
