### ISSUE TITLE
[BUG] Brand New Installation Bug - smart connect not loading correctly with and empty gui interface.

### ISSUE THREAD

**Issue by Asentient** [brianpetro/smart-connect#30]
**Software:** Smart Connect  
**Version:** 1.2.7

**Problem:**  
The software loads into an empty interface. When launching Smart Connect, the user is presented with a blank screen where no buttons, interfaces, or functionality are accessible. As shown in the attached screenshot, the console does not show any specific errors that might indicate the cause of the issue, but the interface fails to load as expected.

### Expected Behaviour

The expected behaviour is that upon launching Smart Connect:
1. All buttons and interfaces should be visible and functional.
2. The Obsidian plugin should connect seamlessly as intended.

### Steps to Reproduce

1. Install and launch Smart Connect (version 1.2.7).
2. Observe that the interface fails to load properly, leading to a blank screen.

### Screenshots
This shows the smart connect helper as well as the console log:- 
![image](https://github.com/user-attachments/assets/d889779b-eb10-4efd-8fc8-9f9fd0a551e0)

### Environment Details

- **OS:** [Windows 11]
- **Smart Connect Version:** 1.2.7
- **Other relevant details:** [I am a brand new smart connect user]

**Comment by brianpetro** [comment]
Hi @Asentient and thank you for the detailed report 😊

There is a "Console" tab at the top of that screen, next to the current "Elements" tab. Can you click that tab and screenshot what's happening there?

Also, if you haven't already, try the "Reset Settings" button at the bottom of the Smart Connect app.

Looking forward to getting things up and running for you
🌴

**Comment by HLuisPP** [comment]
![smartconnect_app_bug_console](https://github.com/user-attachments/assets/c0f82bb5-55dd-46c5-a335-421a6e22c312)
Same problem and same operational system as above. See here the console screenshot

**Comment by brianpetro** [comment]
@Asentient & @HLuisPP version `1.2.8` is now available and should fix this issue. 

Thanks for bringing this to my attention and the helpful screenshots 😊

🌴

**Comment by Asentient** [comment]
Thank you Brian. That was quite fast! Thumbs up.
