### ISSUE TITLE
Connecting to Ollama

### ISSUE THREAD

**Issue by usernotnull** [brianpetro/smart-connect#31]
Hello.

I am using the plugin `https://github.com/pfrankov/obsidian-local-gpt` to connect to my local ollama qwen2 model.

How can I achieve this same connection to my local model using this smart-connect plugin?

Edit: This plugin doesn't support Ollama as a model platform, perhaps?

Here are my settings:

![image](https://github.com/user-attachments/assets/c4574966-7a9a-4107-9c2a-e1bd80f0cc49)

However I'm getting a 404 in the console log:

![image](https://github.com/user-attachments/assets/4ee971a5-5491-42dd-8a9c-d571c38ba2b5)

**Comment by KrushalPagda** [comment]
Enter the path for Ollama, that is: /api/chat. As well, check that your Ollama is running on port and use the model name with parameters that you want to run.
![image](https://github.com/user-attachments/assets/ed8345c5-0045-4045-b1b4-c7a311d43c94)
