### ISSUE TITLE
Cannot read properties of undefined (reading 'fs')

### ISSUE THREAD

**Issue by Thomatoketchup97** [brianpetro/smart-connect#34]
Hello Brian,

Thank you for your work ! 

When using the non official service and since 1.3.1 update, I have the following error.

![image](https://github.com/user-attachments/assets/d5855707-fc5b-4311-b977-01a3e1063f8b)

Do you know how to solve this ? 

Regards,
Thomas

**Comment by brianpetro** [comment]
Hi @Thomatoketchup97 

Thanks for reporting this. The issue should be fixed in `v1.3.2`.

Thanks for using Smart Connect 😊
🌴

**Comment by Thomatoketchup97** [comment]
Hi ! It worked 👍 

Thank you for your help Brian !

**Comment by christianngarcia** [comment]
Thanks for following up. 😊
