### ISSUE TITLE
remove program

### ISSUE THREAD

**Issue by sedonabullion** [brianpetro/smart-connect#40]
I removed program but still launches at startup is there a removal script for windows?

**Comment by brianpetro** [comment]
You can uninstall using the built-in Windows add/remove programs. 

There is also an option to prevent launch at startup under the "Global Settings" in the app 🌴

**Comment by sedonabullion** [comment]
i did that and it didnt remove the program from startup its disabled but i
want it removed will deleting the folder remove everything?

**Comment by brianpetro** [comment]
The relevant folder is `/Users/NAME/Library/Application Support/smart-connect/` 🌴

**Comment by sedonabullion** [comment]
isnt that for osx? i dont see that in the windows installation

**Comment by sedonabullion** [comment]
it appears to be in appdata/local/smart-connect-updater

**Comment by sedonabullion** [comment]
and also appdata/roaming wow there is stuff all over the place after i
uninstalled
