### ISSUE TITLE
Please cancel suscription

### ISSUE THREAD

**Issue by rtm** [brianpetro/smart-connect#43]
Please cancel my $20/month "Keep Goin'" subscription. I cannot see a way to unsubscribe from your web page (might be a good thing to add). Unfortunately, as much as I understand the whole "bleeding edge" thing, I need a product which is well-supported, well-documented, and functions reliably. I can't really deal with a situation where i wake up in the morning trying to get some work done and end up spending an hour fighting with your software, especially when I'm paying for the privilege. Please let me know when the product has stabilized and I'll be glad to resubscribe.

PS. Please rename the merchant name that appears on my statement from "Dropsi' (what's that?) to something I can recognize, like "Smart Connect", maybe?

**Comment by brianpetro** [comment]
The unsubscribe link (manage subscription) link is in the same email where you received your connection key 🌴
