### ISSUE TITLE
when smart-connect app is running, Mac won’t turn display off

### ISSUE THREAD

**Issue by taofuns** [brianpetro/smart-connect#7]
I use a Mac mini (M1), and when the machine is inactive or locked, my monitor will turn the display off, but if the smart-connect app is running, the Mac won’t turn the display off. I tried closing the smart-connect app, It returned to normal.
![image](https://github.com/brianpetro/smart-connect/assets/80188597/34526888-c0d1-44fc-bfc8-8a1206817641)

please help solve this problem.

**Comment by brianpetro** [comment]
This feature can be turned off here:
![Screenshot 2024-06-01 at 2 32 16 PM](https://github.com/brianpetro/smart-connect/assets/1886014/0502edb6-e0c3-429b-b75c-eb7fdcf72571)
