### ISSUE TITLE
Smartconnections.app site returning privacy error on all browsers

### ISSUE THREAD

**Issue by InquisitiveBadger** [brianpetro/smart-connect#8]
Hi there,

New user here. I love this mem alternative and wanted to purchase a connection key for the Smart Connect app, but it appears your site's security certificate expired/glitched out. Got the usual error:

"Your connection is not private
Attackers might be trying to steal your information from smartconnections.app (for example, passwords, messages, or credit 
cards). [Learn more](chrome-error://chromewebdata/#)

NET::ERR_CERT_DATE_INVALID"

Same on all browsers (Chrome, Firefox, Safari, etc.).

**Comment by brianpetro** [comment]
Thanks for bringing this to my attention!

Updating the certificate now... 🌴

**Comment by brianpetro** [comment]
Updated 😊🌴
